// Generated by https://quicktype.io

export interface PageInfo {
  title?:       string;
  email?:       string;
  short_name?:  string;
  author_name?: string;
  facebook?:    string;
  twitter?:     string;
  instagram?:   string;
  team?:        any[];
}

export interface Product {
  productID_idx?: number;
  cod:           string;
  url:           string;
  title:         string;
  category:      string;
}


export interface DetailsProduct {
  results: ProductDes;
  msg:     string;
}

export interface ProductDes{
  productID:   number;
  productName: string;
  category:    string;
  subtitle1:   string;
  desc1:       string;
  subtitle2:   string;
  desc2:       string;
  overView:    string;
}

